### ISSUE TITLE
Plugin do not run with Eclipse 4.8.0

### ISSUE THREAD

**Issue by JoseIgnacioRF** [dernasherbrezon/eclipse-log-param#5]
This amazingly useful plugin does not work with Eclipse Photon (4.8.0) release.

**Comment by dernasherbrezon** [comment]
Tried in Eclipse 2018-12. Works well. Can you try to install from: ```https://dl.bintray.com/dernasherbrezon/eclipse/```

What error do you see?

**Comment by JoseIgnacioRF** [comment]
Thanks for the answer @dernasherbrezon .
I have installed also from that URL.
There is no visible error. Simply, when you apply this template:
`logger.debug("${enclosing_type}.${enclosing_method}( ${formatted_method_parameters} )");`
The text that is included in my java class is:
`logger.debug("MYCLASSNAME.MYMETHOD( formatted_method_parameters )");`
So... the variables ${enclosing_type} and ${enclosing_method} are properly processed. but ${formatted_method_parameters} is not processed. It seems like if the variable name is not correctly written. (I have tried with different spellings)

**Comment by dernasherbrezon** [comment]
Unable to reproduce in Eclipse Photon. Are you sure plugin is enabled and installed?
